openapi: 3.0.3
info:
  title: Mazee API
  version: 0.0.1
servers:
  - url: http://localhost:4000
paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /version:
    get:
      summary: API version
      operationId: getVersion
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: 0.0.1
