userId:
  in: path
  name: userId
  required: true
  schema: { $ref: "./schemas/primitive/ID.yaml" }

postId:
  in: path
  name: postId
  required: true
  schema: { $ref: "./schemas/primitive/ID.yaml" }

chatId:
  in: path
  name: chatId
  required: true
  schema: { $ref: "./schemas/primitive/ID.yaml" }

limit:
  in: query
  name: limit
  description: Maximum number of items to return (max 100)
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20

after:
  in: query
  name: after
  schema:
    type: string
    description: Return results after the given cursor (for pagination)
