profiles_userId:
  get:
    summary: Get profile by userId
    operationId: getProfile
    tags: [Profiles]
    parameters:
      - $ref: "../components/parameters.yaml#/userId"
    security: [{ bearerAuth: [] }]
    responses:
      "200":
        description: Profile
        content:
          application/json:
            schema: { $ref: "../components/schemas/profile/Profile.yaml" }
      "404": { $ref: "../components/responses.yaml#/NotFound" }
  patch:
    summary: Update own profile
    operationId: updateProfile
    tags: [Profiles]
    parameters:
      - $ref: "../components/parameters.yaml#/userId"
    security: [{ bearerAuth: [] }]
    requestBody:
      required: true
      content:
        application/json:
          schema: { $ref: "../components/schemas/profile/ProfileUpdate.yaml" }
    responses:
      "200":
        description: Updated
        content:
          application/json:
            schema: { $ref: "../components/schemas/profile/Profile.yaml" }
      "403": { $ref: "../components/responses.yaml#/Forbidden" }

profiles_userId_block:
  post:
    summary: Block user
    tags: [Profiles]
    security: [ { bearerAuth: [] } ]
    parameters: [ { $ref: "../components/parameters.yaml#/userId" } ]
    responses: { "204": { description: Blocked } }
  delete:
    summary: Unblock user
    tags: [Profiles]
    security: [ { bearerAuth: [] } ]
    parameters: [ { $ref: "../components/parameters.yaml#/userId" } ]
    responses: { "204": { description: Unblocked } }

profiles_userId_mute:
  post:
    summary: Mute posts/notifications from user
    tags: [Profiles]
    security: [ { bearerAuth: [] } ]
    parameters: [ { $ref: "../components/parameters.yaml#/userId" } ]
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties: { durationHours: { type: integer, minimum: 1 } }
    responses: { "204": { description: Muted } }
