me:
  get:
    summary: Get current user profile
    operationId: getMe
    tags: [Profiles]
    security: [{ bearerAuth: [] }]
    responses:
      "200":
        description: Current profile
        content:
          application/json:
            schema: { $ref: "../components/schemas/profiles/Profile.yaml" }

profiles__userId:
  get:
    summary: Get profile by userId
    operationId: getProfile
    tags: [Profiles]
    parameters:
      - $ref: "../components/parameters.yaml#/userId"
    security: [{ bearerAuth: [] }]
    responses:
      "200":
        description: Profile
        content:
          application/json:
            schema: { $ref: "../components/schemas/profiles/Profile.yaml" }
      "404": { $ref: "../components/responses.yaml#/NotFound" }
  patch:
    summary: Update own profile
    operationId: updateProfile
    tags: [Profiles]
    parameters:
      - $ref: "../components/parameters.yaml#/userId"
    security: [{ bearerAuth: [] }]
    requestBody:
      required: true
      content:
        application/json:
          schema: { $ref: "../components/schemas/profiles/ProfileUpdate.yaml" }
    responses:
      "200":
        description: Updated
        content:
          application/json:
            schema: { $ref: "../components/schemas/profiles/Profile.yaml" }
      "403": { $ref: "../components/responses.yaml#/Forbidden" }
