name: Auto-merge

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-wait-for-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: CI
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 3600
          intervalSeconds: 15

      - name: Merge when labeled "automerge"
        uses: peter-evans/merge@v4
        with:
          commit_message: pull-request-title
          merge_method: squash
          required_labels: automerge
          repo_token: ${{ secrets.GITHUB_TOKEN }}
